### ISSUE TITLE
现在已经无法使用，请问还在维护吗？

### ISSUE THREAD

**Issue by KazeMae** [flben233/HandiSWUST-Android-Rebuild#1]
现在已经无法使用，请问还在维护吗？

**Comment by flben233** [comment]
由于域名过期，原版本已在7.17停止使用，请更新至最新版本，
下载链接: https://wwn.lanzoul.com/b0419zkwh
提取码: 2333

**Comment by flben233** [comment]
github的release忘记传了，一会补上
